services:
  db:
    container_name: postgres
    image: postgres:18
    environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: hong
      POSTGRES_PASSWORD: for_HENNGE
      POSTGRES_DB: honngae_db
    ports:
      - "5432:5432"
    healthcheck:
      # test: ["CMD", "pg_isready -U ${POSTGRES_USER} -d ${honngae_db}"]
      test: ["CMD", "pg_isready -U hong -d honngae_db"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: